### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by oblitum** [josa42/coc-docker#30]
I've setup the server manually with the following configuration and it worked:

```vim
  let languageservers = {}

  if executable('docker-langserver')
    let languageservers['docker'] = {
    \   'command': 'docker-langserver',
    \   'args': ['--stdio'],
    \   'filetypes': ['dockerfile'],
    \   'rootPatterns': ['Dockerfile']
    \ }
  endif

  call coc#config('languageserver', languageservers)
```

Before  that I tried the extension but it didn't work. `:CocCommand docker.version` was the only thing that worked.

I'm not sure whether it relates with the `--node-ipc` option being adopted internally. For manual configuration `--stdio` is the simplest option that's working for me.

**Comment by jameswritescode** [comment]
FWIW part of the issue may be the explicit filetypes that coc-docker specifies here: https://github.com/josa42/coc-docker/blob/master/package.json#L27-L28

1. When I open `Dockerfile` the filetype set is `dockerfile` and this plugin is looking for `Dockerfile` (case matters)
2. `docker-compose.yml` filetype is `yaml` because vim doesn't know that compose files are special, so an autocmd to set it to `yaml.docker-compose` is required

Would be nice if the plugin would use `dockerfile` and if possible activate for `docker-compose.yml` based off file name or document in the `README` the requirement to set the filetype

**Comment by josa42** [comment]
@jameswritescode 

> 1. When I open `Dockerfile` the filetype set is `dockerfile` and this plugin is looking for `Dockerfile` (case matters)

You are right. Turns out  [`polyglot`](https://github.com/sheerun/vim-polyglot/blob/master/ftdetect/polyglot.vim#L331), is using `Dockerfile` as filetype. I missed that.

> 2. `docker-compose.yml` filetype is `yaml` because vim doesn't know that compose files are special, so an autocmd to set it to `yaml.docker-compose` is required

I need to look into that. But, to be honest the `docker-compose.yml` completions provider is experimental and I am not sure if I want to keep it.

`coc-yaml` with a schema is working better for me.

`coc-settings.json`:
```
{
  "yaml.schemas": {
    "https://raw.githubusercontent.com/docker/compose/master/compose/config/config_schema_v3.7.json": "docker-*.yml"
  }
}
```
